version: 0.4.4.dev0

skip_tags: true

matrix:
  fast_finish: true

os: Visual Studio 2015

environment:
  matrix:
    - PLATFORM: "x64"
      VCBUILD: "vcbuild64.bat"
      RUNTEST: "runtest64.bat"
      MINICONDA: C:\\Miniconda3
      PYTHON_VERSION: 3.7

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - "conda create -q -n pylibtiff-dev python=%PYTHON_VERSION% numpy pytest pip libtiff"
  - activate pylibtiff-dev
  - python setup.py develop

build: off

test_script:
  - activate pylibtiff-dev
  - pytest -sv -r s libtiff