skip_tags: true

matrix:
  fast_finish: true

os: Visual Studio 2015

environment:
  matrix:
    - PLATFORM: "x64"
      VCBUILD: "vcbuild64.bat"
      RUNTEST: "runtest64.bat"
      PYTHON: "C:\\Python36-x64"

before_build:
  "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" %PLATFORM%"

build_script:
  - "%PYTHON%\\python.exe -m pip install pytest numpy"
  - "%PYTHON%\\python.exe setup.py develop"
  - "%PYTHON%\\python.exe -m pytest libtiff"
